spring:
  application:
    name: GatedCommunity
  datasource:
    url: jdbc:postgresql://${DB_HOST}/gatedcommunity
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

  servlet:
    multipart:
      max-file-size: 10MB    # Увеличьте лимит на размер загружаемого файла
      max-request-size: 10MB  # Увеличьте лимит на размер запроса

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocol: TLSv1.2
            trust: smtp.gmail.com
          debug: true

#Эта настройка добавляет ко всем энпоэнтам /api
server:
  servlet:
    context-path: /api

key:
  access: ${KEY_ACCESS}
  refresh: ${KEY_REFRESH}

logging:
  file:
    name: logs/log.log
  level:
    root: info


messages:
  hello: hello from Local!
    